version: "3.6"
services:
  postgres2:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/pgsql/data2
    environment:
      POSTGRES_PASSWORD: postgrespassword
    command: -p 5431
    ports:
      - "5431:5431"
  graphql-engine-testing:
    image: hasura/graphql-engine:v2.7.0
    ports:
      - "5001:5001"
    depends_on:
      - "postgres2"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres2:5431/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres2:5431/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_SERVER_PORT: 5001
volumes:
  db_data:
